spring.application.name=booking-service

server.port=${PORT:8084}

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ================= EUREKA =================
eureka.client.service-url.defaultZone=https://skybooker-gj4r.onrender.com/eureka
eureka.instance.prefer-ip-address=true

# ================= RABBITMQ (CloudAMQP) =================
spring.rabbitmq.url=${RABBITMQ_URL}