spring.application.name=skybooker-eureka-server

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}

eureka.server.enable-self-preservation=false