sonar.projectKey=flight-service
sonar.projectName=Flight-Service

sonar.sources=src/main/java

sonar.inclusions=src/main/java/**/service/**

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.host.url=http://localhost:9000

sonar.login=squ_4ff97e04395f176421eb9c77acbb93d02cfdeda9