spring.application.name=SKYBOOKER-AUTH-SERVICE

server.port=${PORT:8081}

# ================= DATABASE (Railway MySQL) =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ================= EUREKA =================
eureka.client.service-url.defaultZone=https://skybooker-gj4r.onrender.com/eureka
eureka.instance.prefer-ip-address=true


# ================= REDIS (OTP) =================
spring.data.redis.url=${REDIS_URL}

# ================= GOOGLE OAUTH =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= LOGGING =================
logging.level.org.springframework.security=INFO